name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test-bot:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'

  # Pull bottles, and push commits after `test-bot` job completes, if:
  # - triggered by pull_request
  # - pull_request is not a draft
  # - pull_request is not from a fork (implies write permission)
  # - pull_request contains `AUTO_MERGE` line in the PR body
  auto-merge:
    needs: test-bot
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:

      - name: Check pull request for AUTO_MERGE line
        id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '^AUTO_MERGE$'
          flags: 'm'

      # Flow below duplicated from `publish.yml` with additional conditions,
      # and an additional checkout of base of the pull request.
      #
      # `brew pr-pull` expects to be run in the context of the base of the pull
      # request, instead of the pull request itself. Since a workflow triggered
      # by a `pull_request` is usually run in the context of the pull request,
      # the base needs to be explicitly checked out. The full depth is needed
      # since `brew pr-pull` uses the diffs with the base to determine which
      # Homebrew formulae have changed and need bottles to be downloaded.

      - name: Check out pull request base
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Set up Homebrew
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: Homebrew/actions/git-user-config@master

      - name: Debug environment
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          git log -3 HEAD
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "> git log -3 \$GITHUB_SHA"
          git log -3 $GITHUB_SHA
          echo "> git log HEAD...\$GITHUB_SHA"
          git log HEAD...$GITHUB_SHA
          echo "> git diff-tree -r --name-only --diff-filter=AM \$GITHUB_SHA HEAD -- Formula"
          git diff-tree -r --name-only --diff-filter=AM $GITHUB_SHA HEAD -- Formula

      - name: Pull bottles
        if: ${{ steps.regex-match.outputs.match != '' }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST

      - name: Push commits
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        if: |
          steps.regex-match.outputs.match != '' &&
          github.event.pull_request.head.repo.full_name == github.repository
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin $BRANCH
